[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chromaplot"
dynamic = ["version"]
description = "A desktop application for creating high-quality chromatography figures"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Billy Hobbs", email = "billyehobbs@gmail.com" }
]

dependencies = [
    "numpy",
    "matplotlib",
    "PyQt5",
]

[project.scripts]
chromaplot = "chromaplot.gui.app:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["chromaplot*"]

[tool.setuptools.package-data]
chromaplot = [
    "resources/*",
]

[tool.setuptools.dynamic]
version = { attr = "chromaplot.__version__" }